import AnimatedText from '@/components/AnimatedText'
import Layout from '@/components/Layout'
import Head from 'next/head'
import React, { useEffect, useRef } from 'react'
import Image from 'next/image'
import profilePic from "../../public/images/profile/developer-pic-2.png"
import { useInView, useMotionValue, useSpring } from 'framer-motion'
import Skills from '@/components/Skills'
import Experience from '@/components/Experience'
import Education from '@/components/Education'
import TransitionEffect from '@/components/TransitionEffect'

const AnimatedNumbers = ({value})=>{
    const ref = useRef(null);
    const motionValue = useMotionValue(0);
    const springValue = useSpring(motionValue,{duration:3000})
    const isInView = useInView(ref,{once:true});

    useEffect(()=>{
        if(isInView){
            motionValue.set(value);
        }
    },[isInView,value,motionValue])

    useEffect(()=>{
        springValue.on("change",(latest)=>{
            if(ref.current && latest.toFixed(0)<= value){
                ref.current.textContent = latest.toFixed(0);
            }
        })
    },[springValue,value])

    return <span ref={ref}></span>
}


const about = () => {
  return (
    <>
    <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
    </Head>
    <TransitionEffect/>
    <main className='flex w-full flex-col items-center justify-center dark:text-light '>
        <Layout className='pt-18 px-5'>
            <AnimatedText text="Professional Journey and Expertise" className='mb-16  lg:!text-6xl sm:!text-5xl xs:!text-4xl sm:mb-8'/>
            <div className='grid w-full grid-cols-8 gap-16 sm:gap-8 '>
                <div className='col-span-3  flex flex-col items-start justify-start xl:col-span-4 md:order-2 md:col-span-8'>
                    <h2 className='mb-4 text-lg font-bold uppercase text-dark/75 dark:text-light/75'>Biography</h2>
                    <p className='font-medium'>
                        Hi, I&apos;m Thimira, a mechanical engineering undergraduate.
                    </p>
                    <p className='font-medium my-4'>
                    My portfolio reflects a blend of creativity and technical finesse, showcasing projects where I&apos;ve harnessed the power of code to bring innovative ideas to life. 
                    From crafting robust algorithms to tinkering with hardware intricacies, I thrive on the challenges that the ever-evolving tech landscape presents.
                    </p>
                    <p className='font-medium'>
                    Join me in exploring the exciting world of computer engineering, where every line of code is a step towards progress. 
                    Let&apos;s build the future together, one project at a time. Welcome to my corner of the digital universe!
                    </p>  
                </div>
                <div className='col-span-3 relative h-max rounded-2xl border-2 border-solid border-dark bg-light p-8 dark:bg-dark
                 dark:border-light xl:col-span-4 md:order-1 md:col-span-8'>
                    <div className='absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-dark dark:bg-light '/>
                        <Image src={profilePic} alt="Profile Picture" className='w-full h-auto rounded-2xl' priority sizes='(max-width:768px) 100vw,(max-width:1200px) 50vw,50vw'/>
                     </div>
                     <div className='col-span-2 flex flex-col items-end justify-between xl:col-span-8 xl:flex-row 
                     xl:items-center md:order-3'>
                        <div className='flex flex-col items-end justify-center xl:items-center'>
                            <span className='inline-bloc text-7xl font-bold md:text-6xl sm:text-5xl xs:text-4xl'>
                                <AnimatedNumbers value={2}/>+
                            </span>
                            <h2 className='text-xl font-medium capitalize text-dark/75 dark:text-light/75 xl:text-center md:text-lg sm:text-base 
                            xs:text-sm'>satisfied clients </h2>
                        </div>
                        <div className='flex flex-col items-end justify-center xl:items-center'>
                            <span className='inline-bloc text-7xl font-bold md:text-6xl sm:text-5xl xs:text-4xl'>
                            <AnimatedNumbers value={6}/>+
                            </span>
                            <h2 className='text-xl font-medium capitalize text-dark/75 dark:text-light/75 xl:text-center md:text-lg sm:text-base 
                            xs:text-sm'>Projects Completed</h2>
                        </div>
                        <div className='flex flex-col items-end justify-center xl:items-center'>
                            <span className='inline-bloc text-7xl font-bold md:text-6xl sm:text-5xl xs:text-4xl'>
                            <AnimatedNumbers value={2}/>+
                            </span>
                            <h2 className='text-xl font-medium capitalize text-dark/75 dark:text-light/75 xl:text-center md:text-lg sm:text-base 
                            xs:text-sm'>Years of Experience</h2>
                        </div>
                     </div>
            </div>
            <Skills/>
            <Experience/>
            <Education/>
        </Layout>
    </main>
    </>
  )
}

export default about