import Head from "next/head";
//import { Inter } from "next/font/google";
import Layout from "@/components/Layout";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import lightrobot from "../../public/images/lightrobot.png";
import darkrobot from "../../public/images/darkrobot.png";
import useThemeSwitcher from "@/components/hooks/useThemeSwitcher";
import TransitionEffect from "@/components/TransitionEffect";

//const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [mode, setMode] = useThemeSwitcher();
  return (
    <>
      <Head>
        <title>Pathirajage Don Dinuk Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-center w-full lg:flex-col">
            <div className="w-1/2 md:w-full ">
              <Image
                src={profilePic}
                alt="image"
                className="w-auto md:p-3 p-20 rounded-full  h-auto lg:w-auto md:inline-block md:w-full"
                priority
                sizes="(max-width:768px) 100vw,(max-width:1200px) 50vw,50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center  lg:w-full lg:text-center">
              <AnimatedText
                text="Turning Thoughts Into Codes"
                className="!text-6xl !text-left 
              xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl "
              />
              <p className="my-4 text-base font-medium md:text-base sm:text-xs">
                As a skilled mechanical engineering undergraduate student, I am
                dedicated to learn and develop my skills in web development
                software engineering and data science related fields. Explore my latest projects and articles,
                showcasing my expertise in various new technology.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center ">
                <Link
                  href="/CV.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 
                  rounded-lg text-lg font-semibold hover:bg-light hover:text-dark 
                  border-2 border-solid border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                  hover:dark:border-light md:p-2 md:px-4 md:text-base "
                  download={true}
                >
                  Resume<LinkArrow className={"w-6 ml-1"}></LinkArrow>
                </Link>
                <Link
                  href="mailto:pathirajadnew@gmail.com"
                  className="flex items-center ml-4 justify-center p-2 px-8
          bg-dark text-light shadow-md border border-solid border-dark w-auto h-[50px] rounded-lg font-semibold hover:bg-light
          hover:text-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
          hover:dark:border-light md:w-12 md:h-12 md:text-[10px]"
                >
                  Hire Me
                </Link>
              </div>
            </div>  
        </div>
        </Layout>
        
        
      </main>

      <div className="absolute right-8 -bottom-4 inline-block w-32 lg:hidden">
          <Image
            src={mode === "dark" ? darkrobot : lightrobot}
            alt="robot"
            className="w-full h-auto"
          />
          </div>
    </>
  );
}
